source ~/dotfiles/repos/antigen/antigen.zsh
source ~/dotfiles/zsh/theme.zsh

# Alias file
source ~/dotfiles/zsh/aliases.zsh

# Antigen
antigen use oh-my-zsh

antigen bundle git
antigen bundle dirhistory
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

clear
